apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus
  name: girus
spec:
  containers:
  - image: alpine
    name: girus
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
